jobs:
  include:
  - stage: deploy
    name: Publish Storybook to Chromatic
    if: type != pull_request OR repo != head_repo
    script: skip
    deploy:
      provider: script
      edge: true
      script: npm run deploy:chromatic -- $( (( $TRAVIS_BRANCH  == 'master' )) && printf %s '--auto-accept-changes' )
      on:
        all_branches: true
